spring:
  application:
    name: eureka-client

server:
  port: 8003

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/

logging:
  level:
    com.redrcd.eurekaservice: debug
    org.springfromework.web: info
  file: ..\log\eureka-client.log