spring:
  application:
    name: feign

server:
  port: 8002

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/

feign:
  hystrix:
    enabled: true

logging:
  level:
    com.redrcd.feign: debug
    org.springfromework.web: info
  file: ..\log\feign.log