server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
#  profiles:    #Config Server会默认从应用的src/main/resource目录下检索配置文件。也可以通过spring.cloud.config.server.native.searchLocations=file:E:/properties/属性来指定配置文件的位置。
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/youxinzhu/cloudsample/
          search-paths: config-repo
          username: youxinzhu110@126.com
          password: 7aq283jyou
